// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: epcachepb.proto

package epcachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EPCacheClient is the client API for EPCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EPCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type ePCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewEPCacheClient(cc grpc.ClientConnInterface) EPCacheClient {
	return &ePCacheClient{cc}
}

func (c *ePCacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/epcachepb.EPCache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EPCacheServer is the server API for EPCache service.
// All implementations must embed UnimplementedEPCacheServer
// for forward compatibility
type EPCacheServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedEPCacheServer()
}

// UnimplementedEPCacheServer must be embedded to have forward compatible implementations.
type UnimplementedEPCacheServer struct {
}

func (UnimplementedEPCacheServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEPCacheServer) mustEmbedUnimplementedEPCacheServer() {}

// UnsafeEPCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EPCacheServer will
// result in compilation errors.
type UnsafeEPCacheServer interface {
	mustEmbedUnimplementedEPCacheServer()
}

func RegisterEPCacheServer(s grpc.ServiceRegistrar, srv EPCacheServer) {
	s.RegisterService(&EPCache_ServiceDesc, srv)
}

func _EPCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EPCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/epcachepb.EPCache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EPCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// EPCache_ServiceDesc is the grpc.ServiceDesc for EPCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EPCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "epcachepb.EPCache",
	HandlerType: (*EPCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EPCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "epcachepb.proto",
}
